Avoid double encoding when publishing content (#244)
* Install pytest <4.1.0 due to breaking changes with test set up

When running the tests with pytest 4.1.0, we get the following error:

```
request = <SubRequest 'celery_app' for <Function test_startup_event>>
celery_config = {'broker_url': 'pyamqp://', 'result_backend': 'db+postgresql://cnxarchive@localhost/cnxarchive-testing'}
celery_parameters = {'name': 'tasks', 'task_cls': <class 'cnxpublishing.tasks.PyramidAwareTask'>}, celery_enable_logging = False, use_celery_app_trap = False

    @pytest.fixture()
    def celery_app(request,
                   celery_config,
                   celery_parameters,
                   celery_enable_logging,
                   use_celery_app_trap):
        """Fixture creating a Celery application instance."""
>       mark = request.node.get_marker('celery')
E       AttributeError: 'Function' object has no attribute 'get_marker'
```

An example test with this error is `cnxpublishing/tests/test_subscribers.py::test_startup_event`.

* Avoid double encoding when publishing content

In python 2, when calling `str(DocumentContentFormatter())`, the result
is already encoded, so calling `.encode('utf-8')` breaks when there are
unicode character:

```
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/tasks.py", line 31, in __call__
    return super(PyramidAwareTask, self).__call__(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 74, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/subscribers.py", line 167, in baking_processor
    bake(binder, recipe_id, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/bake.py", line 85, in bake
    publish_composite_model(cursor, doc, binder, publisher, message)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/publish.py", line 394, in publish_composite_model
    fileid, _ = _insert_file(cursor, io.BytesIO(html.encode('utf-8')),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 2206: ordinal not in range(128)
```

The reason this used to work is `DocumentContentFormatter` used to return an
ascii string (with `&#920;` instead of Θ) which does not output any errors in
python 2 if it is encoded twice.

By explicitly using `bytes(DocumentContentFormatter())`, we can keep the
type the same in python 2 and 3, so we know not to call `.encode()` on
the result.

* Install the correct version of pytest in .travis.yml

Instead of doing `pip install -U pytest`, which ignores the version
specified in setup.py, uninstall pytest before anything else and use
`pip install .[test]`.