Avoid double encoding when publishing content
In python 2, when calling `str(DocumentContentFormatter())`, the result
is already encoded, so calling `.encode('utf-8')` breaks when there are
unicode character:

```
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/tasks.py", line 31, in __call__
    return super(PyramidAwareTask, self).__call__(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 74, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/subscribers.py", line 167, in baking_processor
    bake(binder, recipe_id, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/bake.py", line 85, in bake
    publish_composite_model(cursor, doc, binder, publisher, message)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/publish.py", line 394, in publish_composite_model
    fileid, _ = _insert_file(cursor, io.BytesIO(html.encode('utf-8')),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 2206: ordinal not in range(128)
```

The reason this used to work is `DocumentContentFormatter` used to return an
ascii string (with `&#920;` instead of Θ) which does not output any errors in
python 2 if it is encoded twice.

By explicitly using `bytes(DocumentContentFormatter())`, we can keep the
type the same in python 2 and 3, so we know not to call `.encode()` on
the result.