Install pytest <4.1.0 due to breaking changes with test set up
When running the tests with pytest 4.1.0, we get the following error:

```
request = <SubRequest 'celery_app' for <Function test_startup_event>>
celery_config = {'broker_url': 'pyamqp://', 'result_backend': 'db+postgresql://cnxarchive@localhost/cnxarchive-testing'}
celery_parameters = {'name': 'tasks', 'task_cls': <class 'cnxpublishing.tasks.PyramidAwareTask'>}, celery_enable_logging = False, use_celery_app_trap = False

    @pytest.fixture()
    def celery_app(request,
                   celery_config,
                   celery_parameters,
                   celery_enable_logging,
                   use_celery_app_trap):
        """Fixture creating a Celery application instance."""
>       mark = request.node.get_marker('celery')
E       AttributeError: 'Function' object has no attribute 'get_marker'
```

An example test with this error is `cnxpublishing/tests/test_subscribers.py::test_startup_event`.