Bypass celery error when queueing books for post publication (#260)
This is the traceback from channel processing from this bit of code:

```
state = celery_app.AsyncResult(result[0]).state
```

```
2019-11-04 18:21:45,205 ERROR [channel_processing][MainThread] Logging an uncaught exception
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/scripts/channel_processing.py", line 96, in processor
    registry.notify(event)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/pyramid/registry.py", line 109, in notify
    [_ for _ in self.subscribers(events, None)]
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 74, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/subscribers.py", line 43, in post_publication_processing
    state = celery_app.AsyncResult(result[0]).state
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/result.py", line 473, in state
    return self._get_task_meta()['status']
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/result.py", line 412, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/backends/base.py", line 386, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 53, in _inner
    return fun(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 130, in _get_task_meta_for
    return self.meta_from_decoded(task.to_dict())
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/backends/base.py", line 301, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/backends/base.py", line 281, in exception_to_python
    exc = cls(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
  File "src/lxml/parser.pxi", line 12, in lxml.etree.ParseError.__init__
TypeError: __init__() takes at least 5 positional arguments (2 given)
```

This happens when `celery_taskmeta` table `result` column has this
value:

```
\x80027d710128580b0000006578635f6d6573736167657102285505617363696971035833000000496e74726f64756374696f6e20746f2044796e616d6963733a204e6577746f6ee2809973204c617773206f66204d6f74696f6e71044b204b2155196f7264696e616c206e6f7420696e2072616e67652831323829710574580a0000006578635f6d6f64756c657106550a657863657074696f6e7358080000006578635f7479706571075512556e69636f6465456e636f64654572726f72752e
```

Since we don't care about getting the exception from celery, I'm
changing the query to directly get the `status` column from the
`celery_taskmeta` table so we can bypass this celery error.